package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelHeavyPump.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelHeavyPump {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape2b, Shape2c, Shape1a, Shape3, Shape3a, Shape3b, Shape3c, Shape3d, Shape3e, Shape4, Shape4a, Shape4b, Shape4c. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape2b", "shape2c", "shape1a", "shape3", "shape3a", "shape3b", "shape3c", "shape3d", "shape3e", "shape4", "shape4a", "shape4b", "shape4c"};

    private ModelHeavyPump() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 19).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(10, 37).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(7F, 9F, 7F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(-8F, 9F, 7F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(5, 37).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(-8F, 9F, -8F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(15, 37).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(7F, 9F, -8F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 53).mirror().addBox(-5F, 0F, -5F, 10F, 13F, 10F), PartPose.offsetAndRotation(0F, 9.5F, 0F, 0F, 0.3927F, 0F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 77).mirror().addBox(-1F, 0F, -1F, 2F, 17F, 2F), PartPose.offset(0F, 7.5F, 0F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 77).mirror().addBox(-1F, 0F, -1F, 2F, 17F, 2F), PartPose.offsetAndRotation(0F, 7.5F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 53).mirror().addBox(-5F, 0F, -5F, 10F, 13F, 10F), PartPose.offsetAndRotation(0F, 9.5F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("shape3d", CubeListBuilder.create().texOffs(0, 53).mirror().addBox(-5F, 0F, -5F, 10F, 13F, 10F), PartPose.offsetAndRotation(0F, 9.5F, 0F, 0F, 1.1781F, 0F));
        root.addOrReplaceChild("shape3e", CubeListBuilder.create().texOffs(0, 53).mirror().addBox(-5F, 0F, -5F, 10F, 13F, 10F), PartPose.offset(0F, 9.5F, 0F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(66, 31).mirror().addBox(0F, 0F, 0F, 14F, 14F, 1F), PartPose.offset(-7F, 9F, 7F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(97, 0).mirror().addBox(0F, 0F, 0F, 1F, 14F, 14F), PartPose.offset(7F, 9F, -7F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(97, 31).mirror().addBox(0F, 0F, 0F, 14F, 14F, 1F), PartPose.offset(-7F, 9F, -8F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 1F, 14F, 14F), PartPose.offset(-8F, 9F, -7F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
