package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelProcessor.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelProcessor {
    /** Part names, in the original's field order: Shape2a, Shape2b, Shape3, Shape3a, Shape3b, Shape3c, Shape2, Shape2c, Shape2d, Shape1, Shape1a, Shape1b, Shape1c. */
    public static final String[] PARTS = {"shape2a", "shape2b", "shape3", "shape3a", "shape3b", "shape3c", "shape2", "shape2c", "shape2d", "shape1", "shape1a", "shape1b", "shape1c"};

    private ModelProcessor() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(36, 47).mirror().addBox(0F, 0F, 0F, 1F, 14F, 7F), PartPose.offset(-0.5F, 9F, -7F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(31, 18).mirror().addBox(0F, 0F, 0F, 1F, 14F, 7F), PartPose.offset(-8F, 9F, -7F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 47).mirror().addBox(0F, 0F, 0F, 16F, 14F, 1F), PartPose.offset(-8F, 9F, -8F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 95).mirror().addBox(0F, 0F, 0F, 14F, 11F, 1F), PartPose.offset(-7F, 12F, 1F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 63).mirror().addBox(0F, 0F, 0F, 14F, 11F, 1F), PartPose.offset(-7F, 12F, 7F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(0F, 0F, 0F, 16F, 14F, 1F), PartPose.offset(-8F, 9F, 0F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(50, 19).mirror().addBox(0F, 0F, 0F, 1F, 11F, 5F), PartPose.offset(-7F, 12F, 2F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(0F, 0F, 0F, 1F, 14F, 7F), PartPose.offset(7F, 9F, -7F));
        root.addOrReplaceChild("shape2d", CubeListBuilder.create().texOffs(18, 19).mirror().addBox(0F, 0F, 0F, 1F, 11F, 5F), PartPose.offset(6F, 12F, 2F));
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(54, 10).mirror().addBox(0F, 0F, 0F, 14F, 1F, 7F), PartPose.offset(-7F, 11F, 1F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(0F, 0F, 0F, 16F, 1F, 9F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 9F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(54, 0).mirror().addBox(0F, 0F, 0F, 14F, 1F, 7F), PartPose.offset(-7F, 23F, 1F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
