package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelSolarExchanger.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelSolarExchanger {
    /** Part names, in the original's field order: Shape2, Shape2a, Shape1, Shape1a, Shape1b, Shape1c, Shape1d, Shape1e, Shape1f, Shape1g, Shape3, Shape3a, Shape3b, Shape3c, Shape4, Shape5, Shape5a, Shape5b, Shape5c, Shape5d, Shape5e, Shape5f, Shape5g. */
    public static final String[] PARTS = {"shape2", "shape2a", "shape1", "shape1a", "shape1b", "shape1c", "shape1d", "shape1e", "shape1f", "shape1g", "shape3", "shape3a", "shape3b", "shape3c", "shape4", "shape5", "shape5a", "shape5b", "shape5c", "shape5d", "shape5e", "shape5f", "shape5g"};

    private ModelSolarExchanger() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 55).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 55).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(67, 98).mirror().addBox(-0.5F, -6F, 0F, 1F, 6F, 14F), PartPose.offsetAndRotation(4F, 23.5F, -7F, 0F, 0F, 0.5236F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(67, 76).mirror().addBox(-0.5F, 0F, 0F, 1F, 6F, 14F), PartPose.offsetAndRotation(4F, 8.5F, -7F, 0F, 0F, -0.5236F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(67, 0).mirror().addBox(0F, 0F, -0.5F, 14F, 6F, 1F), PartPose.offsetAndRotation(-7F, 8.5F, 4F, 0.5236F, 0F, 0F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(67, 8).mirror().addBox(0F, -6F, -0.5F, 14F, 6F, 1F), PartPose.offsetAndRotation(-7F, 23.5F, 4F, -0.5236F, 0F, 0F));
        root.addOrReplaceChild("shape1d", CubeListBuilder.create().texOffs(67, 32).mirror().addBox(-0.5F, 0F, 0F, 1F, 6F, 14F), PartPose.offsetAndRotation(-4F, 8.5F, -7F, 0F, 0F, 0.5236F));
        root.addOrReplaceChild("shape1e", CubeListBuilder.create().texOffs(67, 16).mirror().addBox(0F, 0F, -0.5F, 14F, 6F, 1F), PartPose.offsetAndRotation(-7F, 8.5F, -4F, -0.5236F, 0F, 0F));
        root.addOrReplaceChild("shape1f", CubeListBuilder.create().texOffs(67, 54).mirror().addBox(-0.5F, -6F, 0F, 1F, 6F, 14F), PartPose.offsetAndRotation(-4F, 23.5F, -7F, 0F, 0F, -0.5236F));
        root.addOrReplaceChild("shape1g", CubeListBuilder.create().texOffs(67, 24).mirror().addBox(0F, -6F, -0.5F, 14F, 6F, 1F), PartPose.offsetAndRotation(-7F, 23.5F, -4F, 0.5236F, 0F, 0F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(20, 30).mirror().addBox(0F, 0F, 0F, 2F, 14F, 2F), PartPose.offset(5.5F, 9F, 5.5F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(30, 30).mirror().addBox(0F, 0F, 0F, 2F, 14F, 2F), PartPose.offset(-7.5F, 9F, 5.5F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(10, 30).mirror().addBox(0F, 0F, 0F, 2F, 14F, 2F), PartPose.offset(-7.5F, 9F, -7.5F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 30).mirror().addBox(0F, 0F, 0F, 2F, 14F, 2F), PartPose.offset(5.5F, 9F, -7.5F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 14F, 5F, 14F), PartPose.offset(-7F, 13.5F, -7F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(6.2F, 13.5F, -3F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-3F, 13.5F, 6.2F));
        root.addOrReplaceChild("shape5b", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(2F, 13.5F, -7.2F));
        root.addOrReplaceChild("shape5c", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(2F, 13.5F, 6.2F));
        root.addOrReplaceChild("shape5d", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-3F, 13.5F, -7.2F));
        root.addOrReplaceChild("shape5e", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-7.2F, 13.5F, -3F));
        root.addOrReplaceChild("shape5f", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-7.2F, 13.5F, 2F));
        root.addOrReplaceChild("shape5g", CubeListBuilder.create().texOffs(0, 21).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(6.2F, 13.5F, 2F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
