package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelReactorPump.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelReactorPump {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape3, Shape3a, Shape3b, Shape3d, Shape3c, Shape1a, Shape3e, Shape3f, Shape3g, Shape3h, Shape3i, Shape3j, Shape3k, Shape3l, Shape3m, Shape3n, Shape3o, Shape3p, Shape3q, Shape3r, Shape3s, Shape3t, Shape3u, Shape3v, Shape3w, Shape3x, Shape3y, Shape3z, Shape3aa, Shape3ab, Shape3ac, Shape3ad, Shape3ae, Shape3af, Shape1b, Shape1c, Shape1d, Shape4, Shape4a, Shape4b, Shape4c, Shape5, Shape5a, Shape6, Shape6a. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape3", "shape3a", "shape3b", "shape3d", "shape3c", "shape1a", "shape3e", "shape3f", "shape3g", "shape3h", "shape3i", "shape3j", "shape3k", "shape3l", "shape3m", "shape3n", "shape3o", "shape3p", "shape3q", "shape3r", "shape3s", "shape3t", "shape3u", "shape3v", "shape3w", "shape3x", "shape3y", "shape3z", "shape3aa", "shape3ab", "shape3ac", "shape3ad", "shape3ae", "shape3af", "shape1b", "shape1c", "shape1d", "shape4", "shape4a", "shape4b", "shape4c", "shape5", "shape5a", "shape6", "shape6a"};

    private ModelReactorPump() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(46, 18).mirror().addBox(0F, 0F, 0F, 6F, 1F, 16F), PartPose.offset(2F, 9F, -8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(-1F, 0F, -1F, 2F, 13F, 2F), PartPose.offsetAndRotation(0F, 10F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(-1F, 0F, -1F, 2F, 13F, 2F), PartPose.offset(0F, 10F, 0F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2F, 0F, -0.5F, 4F, 2F, 1F), PartPose.offsetAndRotation(0F, 11F, 0F, 0F, 2.0944F, 0F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-7F, 0F, -0.5F, 14F, 2F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6F, 0F, -0.5F, 12F, 2F, 1F), PartPose.offsetAndRotation(0F, 19F, 0F, 0F, 2.618F, 0F));
        root.addOrReplaceChild("shape3d", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5F, 0F, -0.5F, 10F, 2F, 1F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 2.618F, 0F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4F, 0F, -0.5F, 8F, 2F, 1F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape3e", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3F, 0F, -0.5F, 6F, 2F, 1F), PartPose.offsetAndRotation(0F, 13F, 0F, 0F, 2.618F, 0F));
        root.addOrReplaceChild("shape3f", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2F, 0F, -0.5F, 4F, 2F, 1F), PartPose.offset(0F, 11F, 0F));
        root.addOrReplaceChild("shape3g", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2F, 0F, -0.5F, 4F, 2F, 1F), PartPose.offsetAndRotation(0F, 11F, 0F, 0F, 1.0472F, 0F));
        root.addOrReplaceChild("shape3h", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3F, 0F, -0.5F, 6F, 2F, 1F), PartPose.offset(0F, 13F, 0F));
        root.addOrReplaceChild("shape3i", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3F, 0F, -0.5F, 6F, 2F, 1F), PartPose.offsetAndRotation(0F, 13F, 0F, 0F, 2.0944F, 0F));
        root.addOrReplaceChild("shape3j", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4F, 0F, -0.5F, 8F, 2F, 1F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape3k", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4F, 0F, -0.5F, 8F, 2F, 1F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 2.0944F, 0F));
        root.addOrReplaceChild("shape3l", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5F, 0F, -0.5F, 10F, 2F, 1F), PartPose.offset(0F, 17F, 0F));
        root.addOrReplaceChild("shape3m", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5F, 0F, -0.5F, 10F, 2F, 1F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 1.0472F, 0F));
        root.addOrReplaceChild("shape3n", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6F, 0F, -0.5F, 12F, 2F, 1F), PartPose.offset(0F, 19F, 0F));
        root.addOrReplaceChild("shape3o", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6F, 0F, -0.5F, 12F, 2F, 1F), PartPose.offsetAndRotation(0F, 19F, 0F, 0F, 1.0472F, 0F));
        root.addOrReplaceChild("shape3p", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-7F, 0F, -0.5F, 14F, 2F, 1F), PartPose.offset(0F, 21F, 0F));
        root.addOrReplaceChild("shape3q", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-7F, 0F, -0.5F, 14F, 2F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 1.0472F, 0F));
        root.addOrReplaceChild("shape3r", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-7F, 0F, -0.5F, 14F, 2F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 2.0944F, 0F));
        root.addOrReplaceChild("shape3s", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-7F, 0F, -0.5F, 14F, 2F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 2.618F, 0F));
        root.addOrReplaceChild("shape3t", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-7F, 0F, -0.5F, 14F, 2F, 1F), PartPose.offsetAndRotation(0F, 21F, 0F, 0F, 0.5236F, 0F));
        root.addOrReplaceChild("shape3u", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6F, 0F, -0.5F, 12F, 2F, 1F), PartPose.offsetAndRotation(0F, 19F, 0F, 0F, 2.0944F, 0F));
        root.addOrReplaceChild("shape3v", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6F, 0F, -0.5F, 12F, 2F, 1F), PartPose.offsetAndRotation(0F, 19F, 0F, 0F, 0.5236F, 0F));
        root.addOrReplaceChild("shape3w", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-6F, 0F, -0.5F, 12F, 2F, 1F), PartPose.offsetAndRotation(0F, 19F, 0F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("shape3x", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5F, 0F, -0.5F, 10F, 2F, 1F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 2.0944F, 0F));
        root.addOrReplaceChild("shape3y", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5F, 0F, -0.5F, 10F, 2F, 1F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("shape3z", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-5F, 0F, -0.5F, 10F, 2F, 1F), PartPose.offsetAndRotation(0F, 17F, 0F, 0F, 0.5236F, 0F));
        root.addOrReplaceChild("shape3aa", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4F, 0F, -0.5F, 8F, 2F, 1F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 1.0472F, 0F));
        root.addOrReplaceChild("shape3ab", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4F, 0F, -0.5F, 8F, 2F, 1F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 0.5236F, 0F));
        root.addOrReplaceChild("shape3ac", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-4F, 0F, -0.5F, 8F, 2F, 1F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 2.618F, 0F));
        root.addOrReplaceChild("shape3ad", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3F, 0F, -0.5F, 6F, 2F, 1F), PartPose.offsetAndRotation(0F, 13F, 0F, 0F, 1.0472F, 0F));
        root.addOrReplaceChild("shape3ae", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3F, 0F, -0.5F, 6F, 2F, 1F), PartPose.offsetAndRotation(0F, 13F, 0F, 0F, 1.5708F, 0F));
        root.addOrReplaceChild("shape3af", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-3F, 0F, -0.5F, 6F, 2F, 1F), PartPose.offsetAndRotation(0F, 13F, 0F, 0F, 0.5236F, 0F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(0, 10).mirror().addBox(0F, 0F, 0F, 4F, 1F, 6F), PartPose.offset(-2F, 9F, 2F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(0F, 0F, 0F, 6F, 1F, 16F), PartPose.offset(-8F, 9F, -8F));
        root.addOrReplaceChild("shape1d", CubeListBuilder.create().texOffs(21, 10).mirror().addBox(0F, 0F, 0F, 4F, 1F, 6F), PartPose.offset(-2F, 9F, -8F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 7).mirror().addBox(0F, 0F, 0F, 4F, 1F, 1F), PartPose.offset(-2F, 8F, 2F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(31, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 6F), PartPose.offset(2F, 8F, -3F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(47, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 6F), PartPose.offset(-3F, 8F, -3F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(0, 4).mirror().addBox(0F, 0F, 0F, 4F, 1F, 1F), PartPose.offset(-2F, 8F, -3F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(35, 56).mirror().addBox(0F, 0F, 0F, 16F, 13F, 1F), PartPose.offset(-8F, 10F, 7F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(0, 56).mirror().addBox(0F, 0F, 0F, 16F, 13F, 1F), PartPose.offset(-8F, 10F, -8F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(32, 72).mirror().addBox(0F, 0F, 0F, 1F, 13F, 14F), PartPose.offset(7F, 10F, -7F));
        root.addOrReplaceChild("shape6a", CubeListBuilder.create().texOffs(0, 72).mirror().addBox(0F, 0F, 0F, 1F, 13F, 14F), PartPose.offset(-8F, 10F, -7F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
