package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelBigTurbine.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelBigTurbine {
    /** Part names, in the original's field order: Shape4, Shape4a, Shape4b, Shape220b. */
    public static final String[] PARTS = {"shape4", "shape4a", "shape4b", "shape220b"};

    private ModelBigTurbine() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(39, 10).mirror().addBox(-4F, 12F, 0F, 8F, 16F, 1F), PartPose.offset(0F, 6F, 6F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(19, 0).mirror().addBox(-22F, -4F, 0F, 44F, 8F, 1F), PartPose.offset(0F, 14F, 6F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(19, 10).mirror().addBox(-4F, -8F, 0F, 8F, 16F, 1F), PartPose.offset(0F, 2F, 6F));
        root.addOrReplaceChild("shape220b", CubeListBuilder.create().texOffs(39, 10).mirror().addBox(-4F, -16F, 0F, 8F, 16F, 1F), PartPose.offsetAndRotation(0F, 34F, 6F, -0.3491F, 0F, 0F));
        return LayerDefinition.create(mesh, 64, 32);
    }
}
