package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelControl.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelControl {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape3, Shape3a, Shape4, Shape4a, Shape4b, Shape5, Shape5a, Shape5b, Shape5c, Shape5d, Shape5e, Shape5f, Shape5g, Shape5h, Shape5i, Shape5j, Shape5k, Shape6, Shape6a, Shape6b, Shape6c, Shape6d, Shape6e, Shape6f, Shape6g, Shape6h, Shape6u, Shape6i, Shape6j, Shape6k, Shape6l, Shape6m, Shape6n, Shape7, Shape7a, Shape7b, Shape7c, Shape8, Shape9, Shape9a. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape3", "shape3a", "shape4", "shape4a", "shape4b", "shape5", "shape5a", "shape5b", "shape5c", "shape5d", "shape5e", "shape5f", "shape5g", "shape5h", "shape5i", "shape5j", "shape5k", "shape6", "shape6a", "shape6b", "shape6c", "shape6d", "shape6e", "shape6f", "shape6g", "shape6h", "shape6u", "shape6i", "shape6j", "shape6k", "shape6l", "shape6m", "shape6n", "shape7", "shape7a", "shape7b", "shape7c", "shape8", "shape9", "shape9a"};

    private ModelControl() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(38, 19).mirror().addBox(0F, 0F, 0F, 2F, 15F, 16F), PartPose.offset(6F, 8F, -8F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 19).mirror().addBox(0F, 0F, 0F, 2F, 15F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(29, 52).mirror().addBox(0F, 0F, 0F, 12F, 15F, 2F), PartPose.offset(-6F, 8F, 6F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 52).mirror().addBox(0F, 0F, 0F, 12F, 15F, 2F), PartPose.offset(-6F, 8F, -8F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 71).mirror().addBox(0F, 0F, 0F, 1F, 15F, 12F), PartPose.offset(3F, 8F, -6F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(0, 71).mirror().addBox(0F, 0F, 0F, 1F, 15F, 12F), PartPose.offset(-4F, 8F, -6F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(0, 99).mirror().addBox(0F, 0F, 0F, 2F, 15F, 12F), PartPose.offset(-1F, 8F, -6F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(4F, 8F, -4F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(74, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-6F, 8F, -1F));
        root.addOrReplaceChild("shape5b", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(-3F, 8F, -4F));
        root.addOrReplaceChild("shape5c", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(1F, 8F, -4F));
        root.addOrReplaceChild("shape5d", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(-6F, 8F, -4F));
        root.addOrReplaceChild("shape5e", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(-6F, 8F, 3F));
        root.addOrReplaceChild("shape5f", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(-3F, 8F, 3F));
        root.addOrReplaceChild("shape5g", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(1F, 8F, 3F));
        root.addOrReplaceChild("shape5h", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 1F), PartPose.offset(4F, 8F, 3F));
        root.addOrReplaceChild("shape5i", CubeListBuilder.create().texOffs(74, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(4F, 8F, -1F));
        root.addOrReplaceChild("shape5j", CubeListBuilder.create().texOffs(74, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(1F, 8F, -1F));
        root.addOrReplaceChild("shape5k", CubeListBuilder.create().texOffs(74, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-3F, 8F, -1F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(4F, 6F, -3F));
        root.addOrReplaceChild("shape6a", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-6F, 6F, -6F));
        root.addOrReplaceChild("shape6b", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-3F, 6F, -6F));
        root.addOrReplaceChild("shape6c", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-6F, 6F, 4F));
        root.addOrReplaceChild("shape6d", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(4F, 6F, -6F));
        root.addOrReplaceChild("shape6e", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(1F, 6F, -6F));
        root.addOrReplaceChild("shape6f", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(1F, 6F, -3F));
        root.addOrReplaceChild("shape6g", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-3F, 6F, -3F));
        root.addOrReplaceChild("shape6h", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-6F, 6F, -3F));
        root.addOrReplaceChild("shape6u", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-6F, 6F, 1F));
        root.addOrReplaceChild("shape6i", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-3F, 6F, 1F));
        root.addOrReplaceChild("shape6j", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(1F, 6F, 1F));
        root.addOrReplaceChild("shape6k", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(4F, 6F, 1F));
        root.addOrReplaceChild("shape6l", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(4F, 6F, 4F));
        root.addOrReplaceChild("shape6m", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(1F, 6F, 4F));
        root.addOrReplaceChild("shape6n", CubeListBuilder.create().texOffs(84, 0).mirror().addBox(0F, 0F, 0F, 2F, 15F, 2F), PartPose.offset(-3F, 6F, 4F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(94, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 10F), PartPose.offset(4.5F, 5.2F, -5F));
        root.addOrReplaceChild("shape7a", CubeListBuilder.create().texOffs(94, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 10F), PartPose.offset(-5.5F, 5.2F, -5F));
        root.addOrReplaceChild("shape7b", CubeListBuilder.create().texOffs(94, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 10F), PartPose.offset(1.5F, 5.2F, -5F));
        root.addOrReplaceChild("shape7c", CubeListBuilder.create().texOffs(94, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 10F), PartPose.offset(-2.5F, 5.2F, -5F));
        root.addOrReplaceChild("shape8", CubeListBuilder.create().texOffs(28, 71).mirror().addBox(0F, 0F, 0F, 12F, 1F, 12F), PartPose.offset(-6F, 4.5F, -6F));
        root.addOrReplaceChild("shape9", CubeListBuilder.create().texOffs(76, 20).mirror().addBox(-1F, 0F, -1F, 2F, 15F, 2F), PartPose.offsetAndRotation(0F, 5F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("shape9a", CubeListBuilder.create().texOffs(76, 20).mirror().addBox(-1F, 0F, -1F, 2F, 15F, 2F), PartPose.offset(0F, 5F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
