package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelCondenser.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelCondenser {
    /** Part names, in the original's field order: Shape2, Shape2a, Shape2b, Shape2c, Shape3, Shape3a, Shape1, Shape4, Shape4a, Shape4b, Shape4c, Shape4d, Shape4e, Shape4f, Shape4g, Shape4h, Shape4i, Shape4j, Shape4k, Shape4l, Shape4m, Shape4n, Shape4o, Shape4p, Shape4q, Shape4r, Shape4s, Shape4t, Shape4u, Shape4w, Shape4x, Shape4y, Shape4z, Shape4aa, Shape4ab, Shape4ac, Shape4ad, Shape4ae, Shape4af, Shape4ag, Shape4ah, Shape4ai, Shape4aj. */
    public static final String[] PARTS = {"shape2", "shape2a", "shape2b", "shape2c", "shape3", "shape3a", "shape1", "shape4", "shape4a", "shape4b", "shape4c", "shape4d", "shape4e", "shape4f", "shape4g", "shape4h", "shape4i", "shape4j", "shape4k", "shape4l", "shape4m", "shape4n", "shape4o", "shape4p", "shape4q", "shape4r", "shape4s", "shape4t", "shape4u", "shape4w", "shape4x", "shape4y", "shape4z", "shape4aa", "shape4ab", "shape4ac", "shape4ad", "shape4ae", "shape4af", "shape4ag", "shape4ah", "shape4ai", "shape4aj"};

    private ModelCondenser() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 2F, 1F, 14F), PartPose.offset(-6F, 22F, -7F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 82).mirror().addBox(0F, 0F, 0F, 2F, 1F, 14F), PartPose.offset(-3F, 22F, -7F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(20, 0).mirror().addBox(0F, 0F, 0F, 2F, 1F, 14F), PartPose.offset(4F, 22F, -7F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 99).mirror().addBox(0F, 0F, 0F, 2F, 1F, 14F), PartPose.offset(1F, 22F, -7F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(60, 0).mirror().addBox(0F, 0F, 0F, 16F, 3F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 22).mirror().addBox(0F, 0F, 0F, 16F, 3F, 16F), PartPose.offset(-8F, 19F, -8F));
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 44).mirror().addBox(0F, 0F, 0F, 12F, 8F, 12F), PartPose.offset(-6F, 11F, -6F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 8F, 1F), PartPose.offset(-4F, 11F, -7F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(0F, 16F, -7F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 8F, 1F), PartPose.offset(6F, 11F, 1F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 6F, 1F), PartPose.offset(4F, 13F, -7F));
        root.addOrReplaceChild("shape4d", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(2F, 11F, -7F));
        root.addOrReplaceChild("shape4e", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 6F, 1F), PartPose.offset(-2F, 11F, -7F));
        root.addOrReplaceChild("shape4f", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(-1F, 16F, -7F));
        root.addOrReplaceChild("shape4g", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(2F, 14F, -7F));
        root.addOrReplaceChild("shape4h", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(0F, 11F, -7F));
        root.addOrReplaceChild("shape4i", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(1F, 14F, -7F));
        root.addOrReplaceChild("shape4j", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 4F, 1F, 1F), PartPose.offset(3F, 12F, -7F));
        root.addOrReplaceChild("shape4k", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 3F), PartPose.offset(6F, 15F, -5F));
        root.addOrReplaceChild("shape4l", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 2F), PartPose.offset(6F, 12F, -6F));
        root.addOrReplaceChild("shape4m", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(5F, 13F, 6F));
        root.addOrReplaceChild("shape4n", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(6F, 13F, -5F));
        root.addOrReplaceChild("shape4o", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(6F, 16F, -3F));
        root.addOrReplaceChild("shape4p", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(6F, 11F, -3F));
        root.addOrReplaceChild("shape4q", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(4F, 11F, 6F));
        root.addOrReplaceChild("shape4r", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 6F, 1F), PartPose.offset(6F, 13F, -1F));
        root.addOrReplaceChild("shape4s", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 3F), PartPose.offset(-7F, 15F, -2F));
        root.addOrReplaceChild("shape4t", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(6F, 13F, -2F));
        root.addOrReplaceChild("shape4u", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 2F), PartPose.offset(6F, 13F, 5F));
        root.addOrReplaceChild("shape4w", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 6F, 1F), PartPose.offset(6F, 13F, 4F));
        root.addOrReplaceChild("shape4x", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 8F, 1F), PartPose.offset(2F, 11F, 6F));
        root.addOrReplaceChild("shape4y", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 8F, 1F), PartPose.offset(0F, 11F, 6F));
        root.addOrReplaceChild("shape4z", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-4F, 11F, 6F));
        root.addOrReplaceChild("shape4aa", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-3F, 14F, 6F));
        root.addOrReplaceChild("shape4ab", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(-2F, 11F, 6F));
        root.addOrReplaceChild("shape4ac", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 7F, 1F), PartPose.offset(-5F, 12F, 6F));
        root.addOrReplaceChild("shape4ad", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(-7F, 11F, -2F));
        root.addOrReplaceChild("shape4ae", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(-7F, 16F, -5F));
        root.addOrReplaceChild("shape4af", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 6F, 1F), PartPose.offset(-7F, 13F, 4F));
        root.addOrReplaceChild("shape4ag", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-7F, 11F, 0F));
        root.addOrReplaceChild("shape4ah", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 4F), PartPose.offset(-7F, 13F, 0F));
        root.addOrReplaceChild("shape4ai", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(-7F, 15F, 1F));
        root.addOrReplaceChild("shape4aj", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 6F, 1F), PartPose.offset(-7F, 11F, -4F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
