package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelDiffuser.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelDiffuser {
    /** Part names, in the original's field order: Shape1, Shape2, Shape1a, Shape3, Shape2a, Shape2b, Shape2c, Shape4, Shape4a, Shape4b, Shape4c, Shape3a, Shape3b, Shape3c, Shape3d, Shape3e, Shape3f, Shape3g, Shape3h, Shape3i, Shape3j, Shape3k, Shape3l, Shape3m, Shape3n, Shape3o, Shape3p, Shape3q, Shape3r, Shape3s, Shape3t, Shape3u, Shape3v, Shape5, Shape5a, Shape5b, Shape5c, Shape5d, Shape5e, Shape5f, Shape5g, Shape5h, Shape5i. */
    public static final String[] PARTS = {"shape1", "shape2", "shape1a", "shape3", "shape2a", "shape2b", "shape2c", "shape4", "shape4a", "shape4b", "shape4c", "shape3a", "shape3b", "shape3c", "shape3d", "shape3e", "shape3f", "shape3g", "shape3h", "shape3i", "shape3j", "shape3k", "shape3l", "shape3m", "shape3n", "shape3o", "shape3p", "shape3q", "shape3r", "shape3s", "shape3t", "shape3u", "shape3v", "shape5", "shape5a", "shape5b", "shape5c", "shape5d", "shape5e", "shape5f", "shape5g", "shape5h", "shape5i"};

    private ModelDiffuser() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(66, 10).mirror().addBox(0F, 0F, 0F, 12F, 7F, 1F), PartPose.offset(-6F, 13F, 7F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(0F, 0F, 0F, 15F, 2F, 15F), PartPose.offset(-7.5F, 9F, -7.5F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 12F, 7F, 1F), PartPose.offset(-6F, 12F, -8F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(10, 36).mirror().addBox(0F, 0F, 0F, 2F, 7F, 2F), PartPose.offset(3F, 11F, 5F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 51).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(0F, 0F, 0F, 15F, 2F, 15F), PartPose.offset(-7.5F, 21F, -7.5F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 70).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(22, 0).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(6.9F, 9F, 6.9F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(22, 0).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(-7.9F, 9F, 6.9F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(22, 0).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(6.9F, 9F, -7.9F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(22, 0).mirror().addBox(0F, 0F, 0F, 1F, 14F, 1F), PartPose.offset(-7.9F, 9F, -7.9F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 36).mirror().addBox(0F, 0F, 0F, 2F, 7F, 2F), PartPose.offset(-1F, 14F, -7F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(4F, 11F, 3F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 36).mirror().addBox(0F, 0F, 0F, 2F, 7F, 2F), PartPose.offset(-5F, 14F, -7F));
        root.addOrReplaceChild("shape3d", CubeListBuilder.create().texOffs(10, 36).mirror().addBox(0F, 0F, 0F, 2F, 7F, 2F), PartPose.offset(-5F, 11F, 5F));
        root.addOrReplaceChild("shape3e", CubeListBuilder.create().texOffs(10, 36).mirror().addBox(0F, 0F, 0F, 2F, 7F, 2F), PartPose.offset(-1F, 11F, 5F));
        root.addOrReplaceChild("shape3f", CubeListBuilder.create().texOffs(0, 46).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-4.5F, 12.5F, -7F));
        root.addOrReplaceChild("shape3g", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(4F, 11F, -4F));
        root.addOrReplaceChild("shape3h", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(1F, 11F, -4F));
        root.addOrReplaceChild("shape3i", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(-2F, 11F, -4F));
        root.addOrReplaceChild("shape3j", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(-5F, 11F, -4F));
        root.addOrReplaceChild("shape3k", CubeListBuilder.create().texOffs(10, 0).mirror().addBox(0F, 0F, 0F, 2F, 10F, 2F), PartPose.offset(4F, 11F, -1F));
        root.addOrReplaceChild("shape3l", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(-5F, 11F, 3F));
        root.addOrReplaceChild("shape3m", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(-2F, 11F, 3F));
        root.addOrReplaceChild("shape3n", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(1F, 11F, 3F));
        root.addOrReplaceChild("shape3o", CubeListBuilder.create().texOffs(10, 0).mirror().addBox(0F, 0F, 0F, 2F, 10F, 2F), PartPose.offset(-6F, 11F, -1F));
        root.addOrReplaceChild("shape3p", CubeListBuilder.create().texOffs(10, 0).mirror().addBox(0F, 0F, 0F, 2F, 10F, 2F), PartPose.offset(-1F, 11F, -1F));
        root.addOrReplaceChild("shape3q", CubeListBuilder.create().texOffs(0, 36).mirror().addBox(0F, 0F, 0F, 2F, 7F, 2F), PartPose.offset(3F, 14F, -7F));
        root.addOrReplaceChild("shape3r", CubeListBuilder.create().texOffs(10, 46).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-4.5F, 17.5F, 6F));
        root.addOrReplaceChild("shape3s", CubeListBuilder.create().texOffs(0, 46).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-0.5F, 12.5F, -7F));
        root.addOrReplaceChild("shape3t", CubeListBuilder.create().texOffs(0, 46).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(3.5F, 12.5F, -7F));
        root.addOrReplaceChild("shape3u", CubeListBuilder.create().texOffs(10, 46).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(3.5F, 17.5F, 6F));
        root.addOrReplaceChild("shape3v", CubeListBuilder.create().texOffs(10, 46).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-0.5F, 17.5F, 6F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(64, 29).mirror().addBox(0F, 0F, 0F, 13F, 1F, 3F), PartPose.offset(-6.5F, 14F, -1.5F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(64, 24).mirror().addBox(0F, 0F, 0F, 13F, 2F, 2F), PartPose.offset(-6.5F, 15F, 2.5F));
        root.addOrReplaceChild("shape5b", CubeListBuilder.create().texOffs(64, 29).mirror().addBox(0F, 0F, 0F, 13F, 1F, 3F), PartPose.offset(-6.5F, 19F, -1.5F));
        root.addOrReplaceChild("shape5c", CubeListBuilder.create().texOffs(64, 29).mirror().addBox(0F, 0F, 0F, 13F, 1F, 3F), PartPose.offset(-6.5F, 17F, -1.5F));
        root.addOrReplaceChild("shape5d", CubeListBuilder.create().texOffs(64, 29).mirror().addBox(0F, 0F, 0F, 13F, 1F, 3F), PartPose.offset(-6.5F, 12F, -1.5F));
        root.addOrReplaceChild("shape5e", CubeListBuilder.create().texOffs(64, 20).mirror().addBox(0F, 0F, 0F, 13F, 1F, 2F), PartPose.offset(-6.5F, 13F, 2.5F));
        root.addOrReplaceChild("shape5f", CubeListBuilder.create().texOffs(64, 20).mirror().addBox(0F, 0F, 0F, 13F, 1F, 2F), PartPose.offset(-6.5F, 18F, 2.5F));
        root.addOrReplaceChild("shape5g", CubeListBuilder.create().texOffs(64, 20).mirror().addBox(0F, 0F, 0F, 13F, 1F, 2F), PartPose.offset(-6.5F, 13F, -4.5F));
        root.addOrReplaceChild("shape5h", CubeListBuilder.create().texOffs(64, 24).mirror().addBox(0F, 0F, 0F, 13F, 2F, 2F), PartPose.offset(-6.5F, 15F, -4.5F));
        root.addOrReplaceChild("shape5i", CubeListBuilder.create().texOffs(64, 20).mirror().addBox(0F, 0F, 0F, 13F, 1F, 2F), PartPose.offset(-6.5F, 18F, -4.5F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
