package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelCentrifuge.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelCentrifuge {
    /** Part names, in the original's field order: Shape2, Shape2a, Shape2b, Shape2c, Shape2d, Shape2e, Shape2f, Shape2g, Shape1, Shape3, Shape3a, Shape3b, Shape3c. */
    public static final String[] PARTS = {"shape2", "shape2a", "shape2b", "shape2c", "shape2d", "shape2e", "shape2f", "shape2g", "shape1", "shape3", "shape3a", "shape3b", "shape3c"};

    private ModelCentrifuge() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(6F, 0F, -3F, 1F, 14F, 6F), PartPose.offset(0F, 9F, 0F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-3F, 0F, 6F, 6F, 14F, 1F), PartPose.offset(0F, 9F, 0F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-7F, 0F, -3F, 1F, 14F, 6F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, -0.7854F, 0F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-3F, 0F, -7F, 6F, 14F, 1F), PartPose.offset(0F, 9F, 0F));
        root.addOrReplaceChild("shape2d", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-7F, 0F, -3F, 1F, 14F, 6F), PartPose.offset(0F, 9F, 0F));
        root.addOrReplaceChild("shape2e", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-7F, 0F, -3F, 1F, 14F, 6F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("shape2f", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-7F, 0F, -3F, 1F, 14F, 6F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, 2.3562F, 0F));
        root.addOrReplaceChild("shape2g", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-7F, 0F, -3F, 1F, 14F, 6F), PartPose.offsetAndRotation(0F, 9F, 0F, 0F, -2.3562F, 0F));
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 61).mirror().addBox(-6F, 0F, -3F, 12F, 1F, 6F), PartPose.offsetAndRotation(0F, 8.5F, 0F, 0F, 0.7854F, 0F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 39).mirror().addBox(-3F, 0F, -6F, 6F, 1F, 12F), PartPose.offsetAndRotation(0F, 8.4F, 0F, 0F, 0.7679F, 0F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 53).mirror().addBox(-6F, 0F, -3F, 12F, 1F, 6F), PartPose.offset(0F, 8.1F, 0F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 69).mirror().addBox(-3F, 0F, -6F, 6F, 1F, 12F), PartPose.offset(0F, 8F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
