package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelSolarTop.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelSolarTop {
    /** Part names, in the original's field order: Shape2, Shape1, Shape1a, Shape1b, Shape1c, Shape3, Shape3a, Shape3b, Shape3c, Shape4, Shape5, Shape5a, Shape5b, Shape5c, Shape5d, Shape5e, Shape5f, Shape5g, Shape5h, Shape5i, Shape5j, Shape5k, Shape5l, Shape5m, Shape5n, Shape5o, Shape5p, Shape5q, Shape5r, Shape5s, Shape5t, Shape5u, Shape5v, Shape5w, Shape5x, Shape5y, Shape5z, Shape5aa, Shape5ab, Shape5ac. */
    public static final String[] PARTS = {"shape2", "shape1", "shape1a", "shape1b", "shape1c", "shape3", "shape3a", "shape3b", "shape3c", "shape4", "shape5", "shape5a", "shape5b", "shape5c", "shape5d", "shape5e", "shape5f", "shape5g", "shape5h", "shape5i", "shape5j", "shape5k", "shape5l", "shape5m", "shape5n", "shape5o", "shape5p", "shape5q", "shape5r", "shape5s", "shape5t", "shape5u", "shape5v", "shape5w", "shape5x", "shape5y", "shape5z", "shape5aa", "shape5ab", "shape5ac"};

    private ModelSolarTop() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 55).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(30, 0).mirror().addBox(-1F, -8.5F, -1F, 2F, 10F, 2F), PartPose.offsetAndRotation(4F, 23F, 4F, -0.3142F, 0F, 0.3142F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-1F, -8.5F, -1F, 2F, 10F, 2F), PartPose.offsetAndRotation(4F, 23F, -4F, 0.3142F, 0F, 0.3142F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(10, 0).mirror().addBox(-1F, -8.5F, -1F, 2F, 10F, 2F), PartPose.offsetAndRotation(-4F, 23F, -4F, 0.3142F, 0F, -0.3142F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(20, 0).mirror().addBox(-1F, -8.5F, -1F, 2F, 10F, 2F), PartPose.offsetAndRotation(-4F, 23F, 4F, -0.3142F, 0F, -0.3142F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(30, 13).mirror().addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(5.5F, 8F, -7.5F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 13).mirror().addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(-7.5F, 8F, -7.5F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(10, 13).mirror().addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(-7.5F, 8F, 5.5F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(20, 13).mirror().addBox(0F, 0F, 0F, 2F, 8F, 2F), PartPose.offset(5.5F, 8F, 5.5F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(40, 0).mirror().addBox(0F, 0F, 0F, 8F, 15F, 8F), PartPose.offset(-4F, 8F, -4F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 7F, 1F), PartPose.offset(4F, 16F, 1F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 8F, 1F), PartPose.offset(4F, 11F, -3F));
        root.addOrReplaceChild("shape5b", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 9F, 1F), PartPose.offset(4F, 8F, 2F));
        root.addOrReplaceChild("shape5c", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(4F, 20F, -1F));
        root.addOrReplaceChild("shape5d", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 2F, 1F, 1F), PartPose.offset(-5F, 18F, 0F));
        root.addOrReplaceChild("shape5e", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(4F, 18F, -2F));
        root.addOrReplaceChild("shape5f", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(4F, 8F, -2F));
        root.addOrReplaceChild("shape5g", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(0F, 14F, -5F));
        root.addOrReplaceChild("shape5h", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 10F, 1F), PartPose.offset(-5F, 13F, 1F));
        root.addOrReplaceChild("shape5i", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(-5F, 20F, -2F));
        root.addOrReplaceChild("shape5j", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 2F, 1F, 1F), PartPose.offset(-5F, 13F, 0F));
        root.addOrReplaceChild("shape5k", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-5F, 12F, -1F));
        root.addOrReplaceChild("shape5l", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(-5F, 18F, -1F));
        root.addOrReplaceChild("shape5m", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-5F, 8F, -2F));
        root.addOrReplaceChild("shape5n", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(-3F, 8F, -5F));
        root.addOrReplaceChild("shape5o", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-2F, 11F, -5F));
        root.addOrReplaceChild("shape5p", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(-1F, 15F, 4F));
        root.addOrReplaceChild("shape5q", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(-1F, 12F, -5F));
        root.addOrReplaceChild("shape5r", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 5F, 1F), PartPose.offset(2F, 18F, -5F));
        root.addOrReplaceChild("shape5s", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(-1F, 17F, -5F));
        root.addOrReplaceChild("shape5t", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(1F, 17F, -5F));
        root.addOrReplaceChild("shape5u", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(-2F, 19F, -5F));
        root.addOrReplaceChild("shape5v", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 7F, 1F), PartPose.offset(-3F, 8F, 4F));
        root.addOrReplaceChild("shape5w", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(1F, 19F, 4F));
        root.addOrReplaceChild("shape5x", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(0F, 11F, 4F));
        root.addOrReplaceChild("shape5y", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(2F, 16F, 4F));
        root.addOrReplaceChild("shape5z", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(-2F, 19F, 4F));
        root.addOrReplaceChild("shape5aa", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(-2F, 14F, 4F));
        root.addOrReplaceChild("shape5ab", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 4F, 1F), PartPose.offset(1F, 8F, 4F));
        root.addOrReplaceChild("shape5ac", CubeListBuilder.create().texOffs(0, 24).mirror().addBox(0F, 0F, 0F, 1F, 3F, 1F), PartPose.offset(1F, 14F, 4F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
