package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelElectrolyzer.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelElectrolyzer {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape3, Shape3a, Shape4, Shape5, Shape5a, Shape6, Shape6a, Shape7, Shape7a, Shape8, Shape8a. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape3", "shape3a", "shape4", "shape5", "shape5a", "shape6", "shape6a", "shape7", "shape7a", "shape8", "shape8a"};

    private ModelElectrolyzer() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 12F, 13F, 12F), PartPose.offset(-6F, 11F, -6F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 25).mirror().addBox(0F, 0F, 0F, 14F, 3F, 1F), PartPose.offset(-7F, 11F, -7F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 25).mirror().addBox(0F, 0F, 0F, 14F, 3F, 1F), PartPose.offset(-7F, 11F, 6F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(50, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 12F), PartPose.offset(6F, 11F, -6F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(50, 0).mirror().addBox(0F, 0F, 0F, 1F, 3F, 12F), PartPose.offset(-7F, 11F, -6F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(78, 0).mirror().addBox(0F, 0F, 0F, 4F, 3F, 4F), PartPose.offset(-2F, 8F, -2F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(0, 30).mirror().addBox(0F, 0F, 0F, 4F, 4F, 2F), PartPose.offset(-2F, 15F, -8F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(0, 30).mirror().addBox(0F, 0F, 0F, 4F, 4F, 2F), PartPose.offset(-2F, 15F, 6F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, 0F, 0F, 2F, 4F, 4F), PartPose.offset(-8F, 15F, -2F));
        root.addOrReplaceChild("shape6a", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, 0F, 0F, 2F, 4F, 4F), PartPose.offset(6F, 15F, -2F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(0, 52).mirror().addBox(0F, 0F, 0F, 8F, 2F, 1F), PartPose.offset(-4F, 9F, -4F));
        root.addOrReplaceChild("shape7a", CubeListBuilder.create().texOffs(0, 47).mirror().addBox(0F, 0F, 0F, 8F, 2F, 1F), PartPose.offset(-4F, 9F, 3F));
        root.addOrReplaceChild("shape8", CubeListBuilder.create().texOffs(29, 30).mirror().addBox(0F, 0F, 0F, 1F, 2F, 6F), PartPose.offset(3F, 9F, -3F));
        root.addOrReplaceChild("shape8a", CubeListBuilder.create().texOffs(13, 30).mirror().addBox(0F, 0F, 0F, 1F, 2F, 6F), PartPose.offset(-4F, 9F, -3F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
