package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelFlywheel.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelFlywheel {
    /** Part names, in the original's field order: Shape1, Shape1a, Shape3, Shape2, Shape2a, Shape2b, Shape2c, Shape2d, Shape2e, Shape2f, Shape2g, Shape2h, Shape2i, Shape2j, Shape2k, Shape2l, Shape2m, Shape2n, Shape2o, Shape2p, Shape3a, Shape3b, Shape3c, Shape3d, Shape3e, Shape3f, Shape3g, Shape3h, Shape3i, Shape3j, Shape3k, Shape3l, Shape3m, Shape3n, Shape3o, Shape3p, Shape4, Shape4a, Shape4b, Shape4c, Shape4d, Shape4e, Shape4f, Shape4g, Shape4h, Shape4i, Shape4j, Shape4k, Shape4l, Shape4m, Shape4n, Shape4o, Shape4p. */
    public static final String[] PARTS = {"shape1", "shape1a", "shape3", "shape2", "shape2a", "shape2b", "shape2c", "shape2d", "shape2e", "shape2f", "shape2g", "shape2h", "shape2i", "shape2j", "shape2k", "shape2l", "shape2m", "shape2n", "shape2o", "shape2p", "shape3a", "shape3b", "shape3c", "shape3d", "shape3e", "shape3f", "shape3g", "shape3h", "shape3i", "shape3j", "shape3k", "shape3l", "shape3m", "shape3n", "shape3o", "shape3p", "shape4", "shape4a", "shape4b", "shape4c", "shape4d", "shape4e", "shape4f", "shape4g", "shape4h", "shape4i", "shape4j", "shape4k", "shape4l", "shape4m", "shape4n", "shape4o", "shape4p"};

    private ModelFlywheel() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2F, -2F, -8.5F, 4F, 4F, 17F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-2F, -2F, -8.5F, 4F, 4F, 17F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(120, 100).mirror().addBox(-15F, 24F, -7F, 30F, 6F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(96, 49).mirror().addBox(-10F, 16F, -7F, 20F, 4F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(166, 22).mirror().addBox(16F, -10F, -7F, 4F, 20F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(10F, 16F, -7F, 4F, 2F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(166, 22).mirror().addBox(-20F, -10F, -7F, 4F, 20F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2d", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-6F, 20F, -7F, 12F, 2F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2e", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-14F, 16F, -7F, 4F, 2F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2f", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(16F, -14F, -7F, 2F, 4F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2g", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(10F, -18F, -7F, 4F, 2F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2h", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-14F, -18F, -7F, 4F, 2F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2i", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(16F, 10F, -7F, 2F, 4F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2j", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-18F, -14F, -7F, 2F, 4F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2k", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-18F, 10F, -7F, 2F, 4F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2l", CubeListBuilder.create().texOffs(96, 49).mirror().addBox(-10F, -20F, -7F, 20F, 4F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2m", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(20F, -6F, -7F, 2F, 12F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2n", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-6F, -22F, -7F, 12F, 2F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2o", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-22F, -6F, -7F, 2F, 12F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape2p", CubeListBuilder.create().texOffs(0, 22).mirror().addBox(-16F, -16F, -7F, 32F, 32F, 14F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(203, 70).mirror().addBox(24F, -15F, -7F, 6F, 30F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(15F, 24F, -7F, 6F, 3F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(203, 70).mirror().addBox(-30F, -15F, -7F, 6F, 30F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3d", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-9F, 30F, -7F, 18F, 3F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3e", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-21F, 24F, -7F, 6F, 3F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3f", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(24F, 15F, -7F, 3F, 6F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3g", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(15F, -27F, -7F, 6F, 3F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3h", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-21F, -27F, -7F, 6F, 3F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3i", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-27F, 15F, -7F, 3F, 6F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3j", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(24F, -21F, -7F, 3F, 6F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3k", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-27F, -21F, -7F, 3F, 6F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3l", CubeListBuilder.create().texOffs(120, 100).mirror().addBox(-15F, -30F, -7F, 30F, 6F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3m", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(30F, -9F, -7F, 3F, 18F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3n", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-9F, -33F, -7F, 18F, 3F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3o", CubeListBuilder.create().texOffs(120, 70).mirror().addBox(-33F, -9F, -7F, 3F, 18F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape3p", CubeListBuilder.create().texOffs(0, 70).mirror().addBox(-24F, -24F, -7F, 48F, 48F, 10F), PartPose.offset(0F, 15F, 2F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 211).mirror().addBox(-22F, 36F, -7F, 44F, 9F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(0, 131).mirror().addBox(-36F, -36F, -7F, 72F, 72F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(160, 167).mirror().addBox(36F, -22F, -7F, 9F, 44F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(22F, 36F, -7F, 9F, 5F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4d", CubeListBuilder.create().texOffs(160, 167).mirror().addBox(-45F, -22F, -7F, 9F, 44F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4e", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-14F, 45F, -3F, 28F, 3F, 6F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape4f", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-31F, 36F, -7F, 9F, 5F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4g", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(22F, -41F, -7F, 9F, 5F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4h", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(36F, -31F, -7F, 5F, 9F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4i", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-31F, -41F, -7F, 9F, 5F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4j", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(36F, 22F, -7F, 5F, 9F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4k", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-41F, -31F, -7F, 5F, 9F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4l", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-41F, 22F, -7F, 5F, 9F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4m", CubeListBuilder.create().texOffs(0, 211).mirror().addBox(-22F, -45F, -7F, 44F, 9F, 6F), PartPose.offset(0F, 15F, 4F));
        root.addOrReplaceChild("shape4n", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(45F, -14F, -3F, 3F, 28F, 6F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape4o", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-14F, -48F, -3F, 28F, 3F, 6F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape4p", CubeListBuilder.create().texOffs(160, 131).mirror().addBox(-48F, -14F, -3F, 3F, 28F, 6F), PartPose.offset(0F, 15F, 0F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
