package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelTurbine.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelTurbine {
    /** Part names, in the original's field order: shaft1, shaft1a. */
    public static final String[] PARTS = {"shaft1", "shaft1a"};

    private ModelTurbine() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shaft1", CubeListBuilder.create().texOffs(0, 106).mirror().addBox(-2F, -2F, 0F, 4F, 4F, 16F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shaft1a", CubeListBuilder.create().texOffs(0, 106).mirror().addBox(-2F, -2F, 0F, 4F, 4F, 16F), PartPose.offset(0F, 15F, -8F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
