package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelExchanger.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelExchanger {
    /** Part names, in the original's field order: Shape1, Shape2b3, Shape1a, Shape2c2, Shape1b, p3, Shape1c, Shape7, Shape2b, Shape2b2, p4, p2, p1, Shape2c, Shape2. */
    public static final String[] PARTS = {"shape1", "shape2b3", "shape1a", "shape2c2", "shape1b", "p3", "shape1c", "shape7", "shape2b", "shape2b2", "p4", "p2", "p1", "shape2c", "shape2"};

    private ModelExchanger() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 11F, -8F));
        root.addOrReplaceChild("shape2b3", CubeListBuilder.create().texOffs(105, 0).mirror().addBox(0F, 0F, 0F, 3F, 14F, 3F), PartPose.offset(-6F, 9F, 3F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape2c2", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(0F, 0F, 0F, 18F, 2F, 18F), PartPose.offset(-9F, 15F, -9F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 20F, -8F));
        root.addOrReplaceChild("p3", CubeListBuilder.create().texOffs(86, 32).mirror().addBox(0F, 0F, 0F, 5F, 8F, 5F), PartPose.offset(2F, 12F, 2F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(66, 46).mirror().addBox(0F, 0F, 0F, 4F, 14F, 4F), PartPose.offset(-2F, 9F, -2F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(79, 0).mirror().addBox(0F, 0F, 0F, 3F, 14F, 3F), PartPose.offset(3F, 9F, -6F));
        root.addOrReplaceChild("shape2b2", CubeListBuilder.create().texOffs(92, 0).mirror().addBox(0F, 0F, 0F, 3F, 14F, 3F), PartPose.offset(3F, 9F, 3F));
        root.addOrReplaceChild("p4", CubeListBuilder.create().texOffs(65, 32).mirror().addBox(0F, 0F, 0F, 5F, 8F, 5F), PartPose.offset(-7F, 12F, 2F));
        root.addOrReplaceChild("p2", CubeListBuilder.create().texOffs(86, 19).mirror().addBox(0F, 0F, 0F, 5F, 8F, 5F), PartPose.offset(2F, 12F, -7F));
        root.addOrReplaceChild("p1", CubeListBuilder.create().texOffs(65, 19).mirror().addBox(0F, 0F, 0F, 5F, 8F, 5F), PartPose.offset(-7F, 12F, -7F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 57).mirror().addBox(0F, 0F, 0F, 16F, 4F, 16F), PartPose.offset(-8F, 14F, -8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(66, 0).mirror().addBox(0F, 0F, 0F, 3F, 14F, 3F), PartPose.offset(-6F, 9F, -6F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
