package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelSteamGrate.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelSteamGrate {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape3, Shape3a, Shape4, Shape7, Shape7a, Shape7b, Shape7c, Shape7d, Shape7e, Shape7f, Shape7g, Shape7h, Shape6, Shape6a, Shape6b. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape3", "shape3a", "shape4", "shape7", "shape7a", "shape7b", "shape7c", "shape7d", "shape7e", "shape7f", "shape7g", "shape7h", "shape6", "shape6a", "shape6b"};

    private ModelSteamGrate() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(63, 72).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(33, 37).mirror().addBox(0F, 0F, 0F, 16F, 15F, 1F), PartPose.offset(-8F, 8F, 7F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(33, 55).mirror().addBox(0F, 0F, 0F, 16F, 15F, 1F), PartPose.offset(-8F, 8F, -8F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(33, 89).mirror().addBox(0F, 0F, 0F, 1F, 15F, 14F), PartPose.offset(-8F, 8F, -7F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 89).mirror().addBox(0F, 0F, 0F, 1F, 15F, 14F), PartPose.offset(7F, 8F, -7F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(64, 0).mirror().addBox(0F, 0F, 0F, 14F, 1F, 14F), PartPose.offset(-7F, 22F, -7F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(4F, 8.2F, -7F));
        root.addOrReplaceChild("shape7a", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(-3.5F, 8.2F, -7F));
        root.addOrReplaceChild("shape7b", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(1F, 8.2F, -7F));
        root.addOrReplaceChild("shape7c", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(-5F, 8.2F, -7F));
        root.addOrReplaceChild("shape7d", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(-6.5F, 8.2F, -7F));
        root.addOrReplaceChild("shape7e", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(5.5F, 8.2F, -7F));
        root.addOrReplaceChild("shape7f", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(2.5F, 8.2F, -7F));
        root.addOrReplaceChild("shape7g", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(-2F, 8.2F, -7F));
        root.addOrReplaceChild("shape7h", CubeListBuilder.create().texOffs(0, 65).mirror().addBox(0F, 0F, 0F, 1F, 1F, 14F), PartPose.offset(-0.5F, 8.2F, -7F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(0, 80).mirror().addBox(0F, 0F, 0F, 14F, 1F, 1F), PartPose.offset(-7F, 8.3F, -4F));
        root.addOrReplaceChild("shape6a", CubeListBuilder.create().texOffs(0, 80).mirror().addBox(0F, 0F, 0F, 14F, 1F, 1F), PartPose.offset(-7F, 8.3F, -0.5F));
        root.addOrReplaceChild("shape6b", CubeListBuilder.create().texOffs(0, 80).mirror().addBox(0F, 0F, 0F, 14F, 1F, 1F), PartPose.offset(-7F, 8.3F, 3F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
