package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelMiniTurbine.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelMiniTurbine {
    /** Part names, in the original's field order: Shape1, Shape1a, Shape2a, Shape2c, Shape2e, Shape2g, Shape2i, Shape2k, Shape2m, Shape3a, Shape2q, Shape2o, Shape3i, Shape3c, Shape3d, Shape3e, Shape3f, Shape3g, Shape3h, Shape3b, Shape4a, Shape4b, Shape4c, Shape4d, Shape4e, Shape4f, Shape4g, Shape4h, Shape6, Shape5. */
    public static final String[] PARTS = {"shape1", "shape1a", "shape2a", "shape2c", "shape2e", "shape2g", "shape2i", "shape2k", "shape2m", "shape3a", "shape2q", "shape2o", "shape3i", "shape3c", "shape3d", "shape3e", "shape3f", "shape3g", "shape3h", "shape3b", "shape4a", "shape4b", "shape4c", "shape4d", "shape4e", "shape4f", "shape4g", "shape4h", "shape6", "shape5"};

    private ModelMiniTurbine() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(16, 0).mirror().addBox(-2F, -2F, 0F, 4F, 4F, 16F), PartPose.offsetAndRotation(0F, 14F, -8F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(16, 0).mirror().addBox(-2F, -2F, 0F, 4F, 4F, 16F), PartPose.offset(0F, 14F, -8F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offset(0F, 14F, 0F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0.3491F));
        root.addOrReplaceChild("shape2e", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 0.6981F));
        root.addOrReplaceChild("shape2g", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 1.0472F));
        root.addOrReplaceChild("shape2i", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 1.3963F));
        root.addOrReplaceChild("shape2k", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 1.7453F));
        root.addOrReplaceChild("shape2m", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 2.0944F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, -2.0944F));
        root.addOrReplaceChild("shape2q", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 2.7925F));
        root.addOrReplaceChild("shape2o", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-0.5F, -16F, -3F, 1F, 32F, 6F), PartPose.offsetAndRotation(0F, 14F, 0F, 0F, 0F, 2.4435F));
        root.addOrReplaceChild("shape3i", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, -0.3491F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, -2.4435F));
        root.addOrReplaceChild("shape3d", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, 1.3963F));
        root.addOrReplaceChild("shape3e", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, -1.3963F));
        root.addOrReplaceChild("shape3f", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, 2.0944F));
        root.addOrReplaceChild("shape3g", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, 2.4435F));
        root.addOrReplaceChild("shape3h", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, -3.5F, 0F, 0F, 0.3491F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(16, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offset(0F, 14F, -3.5F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 2.5307F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 2.9234F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 0.9599F));
        root.addOrReplaceChild("shape4d", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 1.7453F));
        root.addOrReplaceChild("shape4e", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 0.1745F));
        root.addOrReplaceChild("shape4f", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 0.5672F));
        root.addOrReplaceChild("shape4g", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 1.3526F));
        root.addOrReplaceChild("shape4h", CubeListBuilder.create().texOffs(24, 21).mirror().addBox(-0.5F, -12F, -3F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 14F, 7.5F, 0F, 0F, 2.138F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(20, 48).mirror().addBox(-3F, -3F, 0F, 6F, 6F, 3F), PartPose.offset(0F, 14F, 4F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(0, 48).mirror().addBox(-3F, -3F, 0F, 6F, 6F, 3F), PartPose.offset(0F, 14F, -7F));
        return LayerDefinition.create(mesh, 64, 64);
    }
}
