package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelWasteStorage.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelWasteStorage {
    /** Part names, in the original's field order: Shape1, Shape2, Shape3, Shape4, Shape5, Shape6, Shape3a, Shape4a, Shape5a, Shape6a, Shape1a, Shape7, Shape7a, Shape7b, Shape7c, Shape7d, Shape7e, Shape7f, Shape7g. */
    public static final String[] PARTS = {"shape1", "shape2", "shape3", "shape4", "shape5", "shape6", "shape3a", "shape4a", "shape5a", "shape6a", "shape1a", "shape7", "shape7a", "shape7b", "shape7c", "shape7d", "shape7e", "shape7f", "shape7g"};

    private ModelWasteStorage() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(15, 38).mirror().addBox(0F, 0F, -1F, 2F, 16F, 1F), PartPose.offset(-1F, 8F, 8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, -1F, 16F, 16F, 2F), PartPose.offset(-8F, 8F, 0F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(37, 19).mirror().addBox(0F, 0F, -1F, 14F, 16F, 2F), PartPose.offset(-7F, 8F, 2F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(70, 19).mirror().addBox(0F, 0F, -1F, 12F, 16F, 2F), PartPose.offset(-6F, 8F, 4F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(99, 19).mirror().addBox(0F, 0F, -1F, 10F, 16F, 1F), PartPose.offset(-5F, 8F, 6F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(0, 38).mirror().addBox(0F, 0F, -1F, 6F, 16F, 1F), PartPose.offset(-3F, 8F, 7F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(37, 0).mirror().addBox(0F, 0F, -1F, 14F, 16F, 2F), PartPose.offset(-7F, 8F, -2F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(70, 0).mirror().addBox(0F, 0F, -1F, 12F, 16F, 2F), PartPose.offset(-6F, 8F, -4F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(99, 0).mirror().addBox(0F, 0F, -1F, 10F, 16F, 1F), PartPose.offset(-5F, 8F, -5F));
        root.addOrReplaceChild("shape6a", CubeListBuilder.create().texOffs(0, 19).mirror().addBox(0F, 0F, -1F, 6F, 16F, 1F), PartPose.offset(-3F, 8F, -6F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(15, 19).mirror().addBox(0F, 0F, -1F, 2F, 16F, 1F), PartPose.offset(-1F, 8F, -7F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(0, 56).mirror().addBox(0F, 0F, 0F, 8F, 1F, 15F), PartPose.offset(-4F, 13F, -7.5F));
        root.addOrReplaceChild("shape7a", CubeListBuilder.create().texOffs(0, 74).mirror().addBox(0F, 0F, 0F, 15F, 1F, 8F), PartPose.offset(-7.5F, 22F, -4F));
        root.addOrReplaceChild("shape7b", CubeListBuilder.create().texOffs(0, 56).mirror().addBox(0F, 0F, 0F, 8F, 1F, 15F), PartPose.offset(-4F, 22F, -7.5F));
        root.addOrReplaceChild("shape7c", CubeListBuilder.create().texOffs(0, 56).mirror().addBox(0F, 0F, 0F, 8F, 1F, 15F), PartPose.offset(-4F, 18F, -7.5F));
        root.addOrReplaceChild("shape7d", CubeListBuilder.create().texOffs(0, 56).mirror().addBox(0F, 0F, 0F, 8F, 1F, 15F), PartPose.offset(-4F, 9F, -7.5F));
        root.addOrReplaceChild("shape7e", CubeListBuilder.create().texOffs(0, 74).mirror().addBox(0F, 0F, 0F, 15F, 1F, 8F), PartPose.offset(-7.5F, 9F, -4F));
        root.addOrReplaceChild("shape7f", CubeListBuilder.create().texOffs(0, 74).mirror().addBox(0F, 0F, 0F, 15F, 1F, 8F), PartPose.offset(-7.5F, 13F, -4F));
        root.addOrReplaceChild("shape7g", CubeListBuilder.create().texOffs(0, 74).mirror().addBox(0F, 0F, 0F, 15F, 1F, 8F), PartPose.offset(-7.5F, 18F, -4F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
