package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelMagnet.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelMagnet {
    /** Part names, in the original's field order: Shape1, Shape1a, Shape1b, Shape1c, Shape1d, Shape1e, Shape3, Shape3a, Shape2a, Shape2, Shape2b, Shape4, Shape4a, Shape4b, Shape4c, Shape4d, Shape2c, Shape2d, Shape2e, Shape2f, Shape2g, Shape2h, Shape2i, Shape2j, Shape2k, Shape4e, Shape4f, Shape4g, Shape4h, Shape4i, Shape4j, Shape4k, Shape4l, Shape4m, Shape4n, Shape4o, Shape4p, Shape4q, Shape4r, Shape4s, Shape1f, Shape1g, Shape3b, Shape1h, Shape1i, Shape3c, Shape1j, Shape1k, Shape5, Shape5a, Shape5b, Shape5d, Shape5e, Shape5f, Shape5g, Shape5h, Shape5i, Shape5j, Shape5k, Shape5l, Shape5m, Shape5n, Shape5o, Shape5p, Shape6, Shape6a, Shape6b, Shape6c, Shape6d, Shape6e, Shape6f, Shape7, Shape7a, Shape7b, Shape7c, Shape7d, Shape7e. */
    public static final String[] PARTS = {"shape1", "shape1a", "shape1b", "shape1c", "shape1d", "shape1e", "shape3", "shape3a", "shape2a", "shape2", "shape2b", "shape4", "shape4a", "shape4b", "shape4c", "shape4d", "shape2c", "shape2d", "shape2e", "shape2f", "shape2g", "shape2h", "shape2i", "shape2j", "shape2k", "shape4e", "shape4f", "shape4g", "shape4h", "shape4i", "shape4j", "shape4k", "shape4l", "shape4m", "shape4n", "shape4o", "shape4p", "shape4q", "shape4r", "shape4s", "shape1f", "shape1g", "shape3b", "shape1h", "shape1i", "shape3c", "shape1j", "shape1k", "shape5", "shape5a", "shape5b", "shape5d", "shape5e", "shape5f", "shape5g", "shape5h", "shape5i", "shape5j", "shape5k", "shape5l", "shape5m", "shape5n", "shape5o", "shape5p", "shape6", "shape6a", "shape6b", "shape6c", "shape6d", "shape6e", "shape6f", "shape7", "shape7a", "shape7b", "shape7c", "shape7d", "shape7e"};

    private ModelMagnet() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(3F, -7.5F, 0F, 18F, 1F, 16F), PartPose.offsetAndRotation(-12F, -13F, -8F, 0F, 0F, 2.3562F));
        root.addOrReplaceChild("shape1a", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(3F, 6.5F, 0F, 18F, 1F, 16F), PartPose.offsetAndRotation(-12F, 45F, -8F, 0F, 0F, -2.3562F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-21F, 6.5F, 0F, 18F, 1F, 16F), PartPose.offsetAndRotation(12F, 45F, -8F, 0F, 0F, 2.3562F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(0F, -6.5F, 0F, 18F, 1F, 16F), PartPose.offset(-9F, 44F, -8F));
        root.addOrReplaceChild("shape1d", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-21F, -7.5F, 0F, 18F, 1F, 16F), PartPose.offsetAndRotation(12F, -13F, -8F, 0F, 0F, -2.3562F));
        root.addOrReplaceChild("shape1e", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(0F, 0.5F, 0F, 18F, 1F, 16F), PartPose.offset(-9F, -7F, -8F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(35, 37).mirror().addBox(-0.5F, -21F, 0F, 1F, 18F, 16F), PartPose.offset(21.7F, 28F, -8F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(35, 37).mirror().addBox(6.5F, -21F, 0F, 1F, 18F, 16F), PartPose.offset(-28.7F, 28F, -8F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(81, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 1F), PartPose.offsetAndRotation(0F, 16F, -7F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(81, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 1F), PartPose.offset(0F, 15F, -7F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(81, 0).mirror().addBox(26.5F, -11F, 0F, 1F, 24F, 1F), PartPose.offsetAndRotation(0F, 15F, -7F, 0F, 0F, -0.7854F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-11F, 27.7F, -3F, 24F, 1F, 1F), PartPose.offsetAndRotation(0F, 15F, -4F, 0F, 0F, 0.8029F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, 27F, -7F, 24F, 1F, 1F), PartPose.offsetAndRotation(0F, 15.5F, 0F, 0F, 0F, 1.5708F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, -28F, -7F, 24F, 1F, 1F), PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, -0.8029F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, 28F, 1F, 24F, 1F, 1F), PartPose.offset(0F, 15F, -8F));
        root.addOrReplaceChild("shape4d", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, -28F, -7F, 24F, 1F, 1F), PartPose.offset(0F, 16F, 0F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(81, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 1F), PartPose.offset(0F, 15F, 6F));
        root.addOrReplaceChild("shape2d", CubeListBuilder.create().texOffs(82, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 2F), PartPose.offset(0F, 15F, 1F));
        root.addOrReplaceChild("shape2e", CubeListBuilder.create().texOffs(82, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 2F), PartPose.offset(0F, 15F, -3F));
        root.addOrReplaceChild("shape2f", CubeListBuilder.create().texOffs(81, 0).mirror().addBox(26.5F, -11F, 0F, 1F, 24F, 1F), PartPose.offsetAndRotation(0F, 15F, 6F, 0F, 0F, -0.7854F));
        root.addOrReplaceChild("shape2g", CubeListBuilder.create().texOffs(82, 0).mirror().addBox(26.5F, -11F, 0F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 15F, 1F, 0F, 0F, -0.7854F));
        root.addOrReplaceChild("shape2h", CubeListBuilder.create().texOffs(82, 0).mirror().addBox(26.5F, -11F, 0F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 15F, -3F, 0F, 0F, -0.7854F));
        root.addOrReplaceChild("shape2i", CubeListBuilder.create().texOffs(81, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 1F), PartPose.offsetAndRotation(0F, 16F, 6F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape2j", CubeListBuilder.create().texOffs(82, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 16F, 1F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape2k", CubeListBuilder.create().texOffs(82, 0).mirror().addBox(27F, -11F, 0F, 1F, 24F, 2F), PartPose.offsetAndRotation(0F, 16F, -3F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape4e", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, 28F, 6F, 24F, 1F, 1F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape4f", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(-12F, 28F, 1F, 24F, 1F, 2F), PartPose.offset(0F, 15F, 0F));
        root.addOrReplaceChild("shape4g", CubeListBuilder.create().texOffs(0, 91).mirror().addBox(-12F, 28F, 1F, 24F, 1F, 2F), PartPose.offset(0F, 15F, -4F));
        root.addOrReplaceChild("shape4h", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-11F, 27.7F, 6F, 24F, 1F, 1F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 0F, 0.8029F));
        root.addOrReplaceChild("shape4i", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(-11F, 27.7F, 1F, 24F, 1F, 2F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 0F, 0.8029F));
        root.addOrReplaceChild("shape4j", CubeListBuilder.create().texOffs(0, 91).mirror().addBox(-11F, 27.7F, -3F, 24F, 1F, 2F), PartPose.offsetAndRotation(0F, 15F, 0F, 0F, 0F, 0.8029F));
        root.addOrReplaceChild("shape4k", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, 27F, 6F, 24F, 1F, 1F), PartPose.offsetAndRotation(0F, 15.5F, 0F, 0F, 0F, 1.5708F));
        root.addOrReplaceChild("shape4l", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(-12F, 27F, 1F, 24F, 1F, 2F), PartPose.offsetAndRotation(0F, 15.5F, 0F, 0F, 0F, 1.5708F));
        root.addOrReplaceChild("shape4m", CubeListBuilder.create().texOffs(0, 91).mirror().addBox(-12F, 27F, -3F, 24F, 1F, 2F), PartPose.offsetAndRotation(0F, 15.5F, 0F, 0F, 0F, 1.5708F));
        root.addOrReplaceChild("shape4n", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, -28F, 6F, 24F, 1F, 1F), PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, -0.8029F));
        root.addOrReplaceChild("shape4o", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(-12F, -28F, 1F, 24F, 1F, 2F), PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, -0.8029F));
        root.addOrReplaceChild("shape4p", CubeListBuilder.create().texOffs(0, 91).mirror().addBox(-12F, -28F, -3F, 24F, 1F, 2F), PartPose.offsetAndRotation(0F, 16F, 0F, 0F, 0F, -0.8029F));
        root.addOrReplaceChild("shape4q", CubeListBuilder.create().texOffs(0, 78).mirror().addBox(-12F, -28F, 6F, 24F, 1F, 1F), PartPose.offset(0F, 16F, 0F));
        root.addOrReplaceChild("shape4r", CubeListBuilder.create().texOffs(0, 91).mirror().addBox(-12F, -28F, -3F, 24F, 1F, 2F), PartPose.offset(0F, 16F, 0F));
        root.addOrReplaceChild("shape4s", CubeListBuilder.create().texOffs(0, 79).mirror().addBox(-12F, -28F, 1F, 24F, 1F, 2F), PartPose.offset(0F, 16F, 0F));
        root.addOrReplaceChild("shape1f", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 24F, 1F, 16F), PartPose.offset(-12F, -13F, -8F));
        root.addOrReplaceChild("shape1g", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-24F, -1F, 0F, 24F, 1F, 16F), PartPose.offsetAndRotation(12F, -13F, -8F, 0F, 0F, -2.3562F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, -24F, 0F, 1F, 24F, 16F), PartPose.offset(27.7F, 28F, -8F));
        root.addOrReplaceChild("shape1h", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-24F, 0F, 0F, 24F, 1F, 16F), PartPose.offsetAndRotation(12F, 45F, -8F, 0F, 0F, 2.3562F));
        root.addOrReplaceChild("shape1i", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, -1F, 0F, 24F, 1F, 16F), PartPose.offsetAndRotation(-12F, -13F, -8F, 0F, 0F, 2.3562F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(0F, -24F, 0F, 1F, 24F, 16F), PartPose.offset(-28.7F, 28F, -8F));
        root.addOrReplaceChild("shape1j", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 24F, 1F, 16F), PartPose.offset(-12F, 44F, -8F));
        root.addOrReplaceChild("shape1k", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 24F, 1F, 16F), PartPose.offsetAndRotation(-12F, 45F, -8F, 0F, 0F, -2.3562F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1.5F, -30.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, -1.9722F));
        root.addOrReplaceChild("shape5a", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1F, -31.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, -2.7576F));
        root.addOrReplaceChild("shape5b", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0F, -31.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, 2.7576F));
        root.addOrReplaceChild("shape5d", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0.5F, -30F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, 1.1781F));
        root.addOrReplaceChild("shape5e", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1F, -29.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, -0.3927F));
        root.addOrReplaceChild("shape5f", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0F, -30.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, 1.9809F));
        root.addOrReplaceChild("shape5g", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1.5F, -30F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, -1.1781F));
        root.addOrReplaceChild("shape5h", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0F, -29.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, 7F, 0F, 0F, 0.3927F));
        root.addOrReplaceChild("shape5i", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1F, -29.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, -0.3927F));
        root.addOrReplaceChild("shape5j", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0F, -29.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, 0.3927F));
        root.addOrReplaceChild("shape5k", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0.5F, -30F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, 1.1781F));
        root.addOrReplaceChild("shape5l", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0F, -30.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, 1.9809F));
        root.addOrReplaceChild("shape5m", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1.5F, -30F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, -1.1781F));
        root.addOrReplaceChild("shape5n", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1.5F, -30.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, -1.9722F));
        root.addOrReplaceChild("shape5o", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(-1F, -31.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, -2.7576F));
        root.addOrReplaceChild("shape5p", CubeListBuilder.create().texOffs(69, 18).mirror().addBox(0F, -31.5F, 0F, 1F, 7F, 1F), PartPose.offsetAndRotation(0F, 15F, -8F, 0F, 0F, 2.7576F));
        root.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(0, 95).mirror().addBox(7.5F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(-10F, 45F, -6F));
        root.addOrReplaceChild("shape6a", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(0F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(5F, 45F, -6F));
        root.addOrReplaceChild("shape6b", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(0F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(-10F, 45F, -6F));
        root.addOrReplaceChild("shape6c", CubeListBuilder.create().texOffs(0, 95).mirror().addBox(0F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(-10F, -14F, -6F));
        root.addOrReplaceChild("shape6d", CubeListBuilder.create().texOffs(0, 95).mirror().addBox(0F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(-10F, -14F, -6F));
        root.addOrReplaceChild("shape6e", CubeListBuilder.create().texOffs(0, 109).mirror().addBox(7.5F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(-10F, -14F, -6F));
        root.addOrReplaceChild("shape6f", CubeListBuilder.create().texOffs(0, 95).mirror().addBox(0F, 0F, 0F, 5F, 1F, 12F), PartPose.offset(5F, -14F, -6F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(35, 95).mirror().addBox(0F, 0F, 0F, 1F, 5F, 12F), PartPose.offset(-29.5F, 21F, -6F));
        root.addOrReplaceChild("shape7a", CubeListBuilder.create().texOffs(62, 95).mirror().addBox(0F, 0F, 0F, 1F, 5F, 12F), PartPose.offset(-29.5F, 13.5F, -6F));
        root.addOrReplaceChild("shape7b", CubeListBuilder.create().texOffs(35, 95).mirror().addBox(0F, 0F, 0F, 1F, 5F, 12F), PartPose.offset(28.5F, 13.5F, -6F));
        root.addOrReplaceChild("shape7c", CubeListBuilder.create().texOffs(35, 95).mirror().addBox(0F, 0F, 0F, 1F, 5F, 12F), PartPose.offset(-29.5F, 6F, -6F));
        root.addOrReplaceChild("shape7d", CubeListBuilder.create().texOffs(62, 95).mirror().addBox(0F, 0F, 0F, 1F, 5F, 12F), PartPose.offset(28.5F, 6F, -6F));
        root.addOrReplaceChild("shape7e", CubeListBuilder.create().texOffs(62, 95).mirror().addBox(0F, 0F, 0F, 1F, 5F, 12F), PartPose.offset(28.5F, 21F, -6F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
