package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelGasCollector.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelGasCollector {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape3, Shape3a, Shape4, Shape4a, Shape4b, Shape4c, Shape4d. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape3", "shape3a", "shape4", "shape4a", "shape4b", "shape4c", "shape4d"};

    private ModelGasCollector() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 16F, 1F, 16F), PartPose.offset(-8F, 23F, -8F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 30).mirror().addBox(0F, 0F, 0F, 16F, 8F, 1F), PartPose.offset(-8F, 23F, 8F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 19).mirror().addBox(0F, 0F, 0F, 16F, 8F, 1F), PartPose.offset(-8F, 23F, -9F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 69).mirror().addBox(0F, 0F, 0F, 1F, 8F, 18F), PartPose.offset(-9F, 23F, -9F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 41).mirror().addBox(0F, 0F, 0F, 1F, 8F, 18F), PartPose.offset(8F, 23F, -9F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(64, 67).mirror().addBox(0F, 0F, 0F, 8F, 5F, 8F), PartPose.offset(-4F, 8F, -4F));
        root.addOrReplaceChild("shape4a", CubeListBuilder.create().texOffs(64, 0).mirror().addBox(0F, 0F, 0F, 16F, 3F, 16F), PartPose.offset(-8F, 20F, -8F));
        root.addOrReplaceChild("shape4b", CubeListBuilder.create().texOffs(64, 20).mirror().addBox(0F, 0F, 0F, 14F, 3F, 14F), PartPose.offset(-7F, 17F, -7F));
        root.addOrReplaceChild("shape4c", CubeListBuilder.create().texOffs(64, 38).mirror().addBox(0F, 0F, 0F, 12F, 2F, 12F), PartPose.offset(-6F, 15F, -6F));
        root.addOrReplaceChild("shape4d", CubeListBuilder.create().texOffs(64, 54).mirror().addBox(0F, 0F, 0F, 10F, 2F, 10F), PartPose.offset(-5F, 13F, -5F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
