package net.scwunge.reactorcraft.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original ModelGenerator.java (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class ModelGenerator {
    /** Part names, in the original's field order: Shape1, Shape2, Shape2a, Shape2b, Shape2c, Shape2d, Shape2e, Shape2f, Shape2g, Shape1b, Shape1c, Shape3, Shape1d, Shape3a, Shape3b, Shape3c, Shape4, Shape5, Shape7, Shape7a, Shape7b, Shape7c. */
    public static final String[] PARTS = {"shape1", "shape2", "shape2a", "shape2b", "shape2c", "shape2d", "shape2e", "shape2f", "shape2g", "shape1b", "shape1c", "shape3", "shape1d", "shape3a", "shape3b", "shape3c", "shape4", "shape5", "shape7", "shape7a", "shape7b", "shape7c"};

    private ModelGenerator() {
    }

    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-8F, -8F, 0F, 16F, 16F, 127F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 1.1781F));
        root.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, -0.7854F));
        root.addOrReplaceChild("shape2a", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, -2.3562F));
        root.addOrReplaceChild("shape2b", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape2c", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("shape2d", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 1.5708F));
        root.addOrReplaceChild("shape2e", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, -1.5708F));
        root.addOrReplaceChild("shape2f", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 3.1707F));
        root.addOrReplaceChild("shape2g", CubeListBuilder.create().texOffs(0, 155).mirror().addBox(-17F, 32F, 0F, 34F, 8F, 128F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 2.3736F));
        root.addOrReplaceChild("shape1b", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-8F, -8F, 0F, 16F, 16F, 127F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape1c", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-8F, -8F, 0F, 16F, 16F, 127F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0.3927F));
        root.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 293).mirror().addBox(-20F, -20F, 0F, 40F, 40F, 116F), PartPose.offsetAndRotation(0F, 0F, 4F, 0F, 0F, 1.1781F));
        root.addOrReplaceChild("shape1d", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(-8F, -8F, 0F, 16F, 16F, 127F), PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("shape3a", CubeListBuilder.create().texOffs(0, 293).mirror().addBox(-20F, -20F, 0F, 40F, 40F, 116F), PartPose.offset(0F, 0F, 4F));
        root.addOrReplaceChild("shape3b", CubeListBuilder.create().texOffs(0, 293).mirror().addBox(-20F, -20F, 0F, 40F, 40F, 116F), PartPose.offsetAndRotation(0F, 0F, 4F, 0F, 0F, 0.7854F));
        root.addOrReplaceChild("shape3c", CubeListBuilder.create().texOffs(0, 293).mirror().addBox(-20F, -20F, 0F, 40F, 40F, 116F), PartPose.offsetAndRotation(0F, 0F, 4F, 0F, 0F, 0.3927F));
        root.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0F, 0F, 0F, 1F, 1F, 1F), PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(288, 0).mirror().addBox(-40F, -40F, 0F, 80F, 80F, 32F), PartPose.offset(0F, 0F, -32F));
        root.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(0, 461).mirror().addBox(-36F, -4F, 0F, 72F, 8F, 1F), PartPose.offsetAndRotation(0F, 0F, 126.7F, 0F, 0F, -0.7854F));
        root.addOrReplaceChild("shape7a", CubeListBuilder.create().texOffs(0, 461).mirror().addBox(-36F, -4F, 0F, 72F, 8F, 1F), PartPose.offset(0F, 0F, 126.8F));
        root.addOrReplaceChild("shape7b", CubeListBuilder.create().texOffs(0, 461).mirror().addBox(-36F, -4F, 0F, 72F, 8F, 1F), PartPose.offsetAndRotation(0F, 0F, 126.9F, 0F, 0F, 1.5708F));
        root.addOrReplaceChild("shape7c", CubeListBuilder.create().texOffs(0, 461).mirror().addBox(-36F, -4F, 0F, 72F, 8F, 1F), PartPose.offsetAndRotation(0F, 0F, 126.7F, 0F, 0F, 0.7854F));
        return LayerDefinition.create(mesh, 512, 512);
    }
}
