"""Converts the original's Techne-exported Java models (Models/Model*.java, ModelBase with LODModelPart boxes) into 1.21
LayerDefinition factories, keeping each part's name, box, pivot, rotation, texture offset and mirror flag.

Usage: python tools/model2java.py <ModelXxx.java> <NewClassName>
Writes src/main/java/net/scwunge/reactorcraft/client/model/<NewClassName>.java. The original renderers draw these after
translate(0, 2, 1), scale(1, -1, -1), translate(0.5, 0.5, 0.5); MachineRenderer does the same.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/main/java/net/scwunge/reactorcraft/client/model"
NUM = r"(-?[0-9.]+)F?"


def num(v):
    s = f"{float(v):.4f}".rstrip("0").rstrip(".")
    return ("0" if s in ("-0", "") else s) + "F"


def convert(source: Path, class_name: str):
    text = source.read_text(encoding="utf-8", errors="replace")
    tex = re.search(r"textureWidth\s*=\s*(\d+);\s*textureHeight\s*=\s*(\d+);", text)
    tw, th = (int(tex.group(1)), int(tex.group(2))) if tex else (64, 32)
    parts = {}
    order = []
    for m in re.finditer(r"(\w+)\s*=\s*new\s+\w+\(this,\s*(\d+),\s*(\d+)\);", text):
        parts[m.group(1)] = {"u": m.group(2), "v": m.group(3), "boxes": [], "pivot": ("0", "0", "0"), "rot": ("0", "0", "0"), "mirror": False}
        order.append(m.group(1))
    for m in re.finditer(r"(\w+)\.addBox\(" + r",\s*".join([NUM] * 6) + r"(?:,\s*" + NUM + r")?\);", text):
        if m.group(1) in parts:
            parts[m.group(1)]["boxes"].append(m.groups()[1:])
    for m in re.finditer(r"(\w+)\.setRotationPoint\(" + r",\s*".join([NUM] * 3) + r"\);", text):
        if m.group(1) in parts:
            parts[m.group(1)]["pivot"] = m.groups()[1:]
    for m in re.finditer(r"(\w+)\.mirror\s*=\s*(true|false);", text):
        if m.group(1) in parts:
            parts[m.group(1)]["mirror"] = m.group(2) == "true"
    for m in re.finditer(r"setRotation\((\w+),\s*" + r",\s*".join([NUM] * 3) + r"\);", text):
        if m.group(1) in parts:
            parts[m.group(1)]["rot"] = m.groups()[1:]
    lines = []
    names = []
    used = set()
    for name in order:
        p = parts[name]
        if not p["boxes"]:
            continue
        key = re.sub(r"[^a-z0-9_]", "_", name.lower())
        while key in used:
            key += "_"
        used.add(key)
        names.append((name, key))
        cube = f"CubeListBuilder.create().texOffs({p['u']}, {p['v']})"
        if p["mirror"]:
            cube += ".mirror()"
        for box in p["boxes"]:
            x, y, z, w, h, d, inflate = box
            if inflate and float(inflate) != 0:
                cube += f".addBox({num(x)}, {num(y)}, {num(z)}, {num(w)}, {num(h)}, {num(d)}, new CubeDeformation({num(inflate)}))"
            else:
                cube += f".addBox({num(x)}, {num(y)}, {num(z)}, {num(w)}, {num(h)}, {num(d)})"
        px, py, pz = p["pivot"]
        rx, ry, rz = p["rot"]
        if any(float(r) != 0 for r in (rx, ry, rz)):
            pose = f"PartPose.offsetAndRotation({num(px)}, {num(py)}, {num(pz)}, {num(rx)}, {num(ry)}, {num(rz)})"
        else:
            pose = f"PartPose.offset({num(px)}, {num(py)}, {num(pz)})"
        lines.append(f'        root.addOrReplaceChild("{key}", {cube}, {pose});')
    deform = "\nimport net.minecraft.client.model.geom.builders.CubeDeformation;" if "CubeDeformation" in "".join(lines) else ""
    src = f"""package net.scwunge.reactorcraft.client.model;
{deform}
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Converted from the original {source.name} (Techne). Generated by tools/model2java.py; do not edit by hand. */
public final class {class_name} {{
    /** Part names, in the original's field order: {", ".join(n for n, _ in names)}. */
    public static final String[] PARTS = {{{", ".join(f'"{k}"' for _, k in names)}}};

    private {class_name}() {{
    }}

    public static LayerDefinition create() {{
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
{chr(10).join(lines)}
        return LayerDefinition.create(mesh, {tw}, {th});
    }}
}}
"""
    src = src.replace("package net.scwunge.reactorcraft.client.model;\n\n\nimport", "package net.scwunge.reactorcraft.client.model;\n\nimport")
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{class_name}.java").write_text(src, encoding="utf-8", newline="\n")
    print(f"{class_name}: {len(names)} parts, texture {tw}x{th}")


if __name__ == "__main__":
    convert(Path(sys.argv[1]), sys.argv[2])
